### PR TITLE
Basic SearchContainer

### PR DESCRIPTION
**Pull request by dalazaro**
Created the search form, take a look! JSON response from the Nutritionix API is set as component state, and logged in the console. Ready to be passed down to Results.

Also, what do about package-lock.json updates? Some dependency updated itself overnight.

### CODE REVIEW

**Comment by ryan-barrett** [comment]
The package.json should be okay, we just have to make sure to either pull to our forks, or update our own dependencies before pushing.

**Comment by dalazaro** [comment]
Yeah I wonder if there's a way of encrypting/hiding the key and ID without having to take it out of the codebase every time we push new code?

**Comment by ryan-barrett** [comment]
One option is just during development we could put them in a separate file as variables, require that file in SearchContainer, and then gitignore the file?

**Comment by dalazaro** [comment]
Sounds good to me!

**Pull request merged**
